name: mygoatmanager
description: "Goat Manager App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: 0.20.2  # Fixed version instead of 'any'
  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7
  pdf: ^3.11.3
  printing: ^5.14.2
  fl_chart: ^0.66.2 
  share_plus:  ^7.2.1
  path_provider: ^2.1.3
  http: ^1.1.0  # Consider upgrading to http: ^1.2.0 if needed
  google_sign_in: ^6.1.0 
  font_awesome_flutter:  ^10.5.0
  url_launcher: ^6.1.12
  video_player:  ^2.8.3
  chewie: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4  # Updated

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/videos/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"